[package]
name = "systemstat"
version = "0.1.3"
authors = [ "Greg V <greg@unrelenting.technology>" ]
keywords = [ "System", "Info" ]
description = "systemstat"
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/myfreeweb/systemstat"
repository = "https://github.com/myfreeweb/systemstat"

[dependencies]
time = "0.1"
chrono = "0.4"
lazy_static = "1.0"
bytesize = "1.0"
libc = "0.2"

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
nom = "3.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["fileapi", "sysinfoapi", "minwindef", "winbase", "winerror", "ws2def", "ws2ipdef"]
